name: Lint commits

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [ master ]

jobs:
  lint-commits:
    uses: theme-my-login/tml-workflows/.github/workflows/lint-commits.yml@main
