name: Lint PR title

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches: [ master ]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      statuses: write

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            ci
            docs
            build
            perf
            refactor
            test
